server:
  port: 8989

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/PersonalDb
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true